/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('FertigeAbgabe.view.MainView', {
    extend: 'Ext.Container',
    alias: 'widget.MainView',

    requires: [
        'Ext.TitleBar',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.carousel.Carousel',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.Button',
        'Ext.field.Email',
        'Ext.dataview.List',
        'Ext.Map',
        'Ext.tab.Bar'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Nick Kupka Abgabe'
            },
            {
                xtype: 'tabpanel',
                items: [
                    {
                        xtype: 'container',
                        title: 'Carousel',
                        iconCls: 'bookmarks',
                        layout: 'fit',
                        items: [
                            {
                                xtype: 'formpanel',
                                layout: 'fit',
                                items: [
                                    {
                                        xtype: 'carousel',
                                        items: [
                                            {
                                                xtype: 'carousel',
                                                itemId: 'mycarousel2',
                                                ui: 'light',
                                                items: [
                                                    {
                                                        xtype: 'textfield',
                                                        label: 'Field'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'carousel',
                                                items: [
                                                    {
                                                        xtype: 'datepickerfield',
                                                        label: 'Field',
                                                        placeHolder: 'mm/dd/yyyy'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'carousel',
                                                items: [
                                                    {
                                                        xtype: 'emailfield',
                                                        label: 'Field',
                                                        placeHolder: 'email@example.com'
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        title: 'Liste',
                        iconCls: 'compose',
                        items: [
                            {
                                xtype: 'textfield',
                                docked: 'top',
                                label: 'Abgabe zu Web Engineering II'
                            },
                            {
                                xtype: 'textfield',
                                docked: 'top',
                                label: 'Nick Kupka'
                            },
                            {
                                xtype: 'textfield',
                                docked: 'top',
                                label: 'Field'
                            }
                        ]
                    },
                    {
                        xtype: 'map',
                        title: 'Maps',
                        iconCls: 'locate',
                        useCurrentLocation: true
                    }
                ],
                tabBar: {
                    docked: 'bottom',
                    layout: {
                        type: 'hbox',
                        pack: 'center'
                    }
                }
            }
        ]
    }

});